Repository the-standard/ibco, pull requests merged in 2022-07, with the labels that each got.

#54 Liquidity position management
  contracts/BondingEvent.sol
  contracts/OperatorStage2.sol
  contracts/RatioCalculator.sol
  contracts/interfaces/API.sol
  contracts/test_utils/SwapManager.sol
  test/bondingEvent.js
  test/bondingReward.js
  test/operatorStage2.js
Labels: ready to go

#51 Stage 3 staking baby
  contracts/Staking.sol
  package-lock.json
  test/common.js
  test/staking.js
Labels: help wanted

#63 Stage one contract restrictions
  contracts/BondingCurve.sol
  contracts/SEuroCalculator.sol
  scripts/deploymentStages.js
  scripts/testnetContractsUserReady.js
  test/bondingCurve.js
  test/seuroOffering.js
  test/seuroRateCalculator.js
Labels: question

#64 Adds OpenZep back to allow ownership transfer.
  contracts/Staking.sol
  test/staking.js
Labels: ready to go
